### PR TITLE
commented out code which was causing Indeed.search to fail while using mo

### PR DESCRIPTION
**Pull request by minhajuddin**
commented out code which was causing Indeed.search to fail while using mongoid 
- removed dependency on ActiveRecord, sacrificing log coloring.

### CODE REVIEW

**Comment by bogdan** [comment]
Why not calling:

``` ruby
if defined?(ActiveRecord) && ActiveRecord::Base.colorize_logging
```

instead of commenting out?

**Comment by minhajuddin** [comment]
I pushed another commit 0f32a2de6f1d340a17d9912a8fbe4e8e8aa54b89 which uses `defined?(Rails::Lo..)`, I changed it to use `Rails::LogSubscriber.colorize_logging` when I found out that `ActiveRecord::Base.colorize_logging` was deprecated (http://apidock.com/rails/ActiveRecord/Base/colorize_logging/class)

**Comment by bogdan** [comment]
It should be:

``` ruby
if Rails.configuration.respond_to?(:colorize_logging) && Rails.configuration.colorize_logging.
```

For Rails 2.3.5 and 3.0.7 compatibility. Where does `LogSubscriber` come from?

**Comment by minhajuddin** [comment]
Thanks for catching that, I thought `LogSubscriber` was a class with an class method `colorize_logging`, turns out it's not. I tweaked the code to use the `Rails.configuration` object as you pointed out.

**Pull request merged**
